### PR TITLE
iOS 9 Support

### PR DESCRIPTION
**Pull request by threePhase**
Looks like a few things changed with iOS 9 & Xcode 7 which required some updates to the project. The following items are addressed with this pull request:

* Add explicit option to disable bitcode in order to maintain iOS 5 support
* Add support for arm64 devices
* Per iOS 9 [requirement](http://stackoverflow.com/a/30915393), added root view controller to dimming window
* In order to satisfy iOS 9 [multitasking requirement](https://developer.apple.com/library/prerelease/ios/documentation/WindowsViews/Conceptual/AdoptingMultitaskingOniPad/index.html), specify app requires full screen

I also went ahead and dropped the armv7 and armv7s architecture requirement in order to support arm64 devices. This also required rebuilding [libwebp](https://github.com/webmproject/libwebp) and [libjpeg-turbo](https://github.com/libjpeg-turbo/libjpeg-turbo), so I went ahead and updated those from their respective master branches. 

I realize the library updates might be a bit much for this request, so please let me know if you want me to break them (or anything else) out into a separate request.

### CODE REVIEW

**Comment by swisspol** [comment]
Thanks for sending this in! For some reason I stopped receiving GitHub notifications for this repo so I wasn't aware of the activity in the past few months.

This is really 2 changes:
- Update the app for iOS 9
- Add support for `arm64`

The series of commits for iOS 9 seem reasonable. Regarding `arm64` support however, I don't wanna do this. It's just too risky. The app was never tested on 64 bit and it's way too risky, and for no reward.

PS: If you need to easily edit your PR branch, check out my app http://gitup.co/ designed for such things :wink:

**Comment by threePhase** [comment]
I have pulled out the commits which add support for `arm64`. Let me know if there are any other issues.

**Comment by swisspol** [comment]
What's the deal with the `_dimmingWindow.rootViewController` change? Does the app crashes if built on latest SDK because of that? The one in the App Store certainly does not.

In any case, I feel this change should be restricted to iOS 9+ or 8+ or whenever that thing became a requirement. There are still some users of ComicFlow on old iOS versions and one must be very careful not to break them.

**Comment by threePhase** [comment]
It seems that for the latest version of the SDK requires that all windows have a root view controller. It seems that there was never a root view controller associated with the dimming window, so I was adding a new one.

If you would like I could wrap the change up in a runtime version check. Maybe something along the lines of [this](http://stackoverflow.com/a/7848772/4590866)?

**Comment by swisspol** [comment]
I just built ComicFlow with Xcode 7.2 and the latest SDKs both for simulator and device. The project builds fine as-is with no warnings outside of one about missing some launch storyboard. You must have changed something in the Xcode settings to make it iOS 9 only maybe.

**Comment by swisspol** [comment]
Note that I just did a series of commits to make the app submittable to the App Store again: that required adding arm64 support, launch screens, etc...

**Pull request closed without merging**
